version: '3.7'

services:
  frontend:
    image: "ghcr.io/papermc/hangar_frontend"
    build:
      context: ../..
      dockerfile: docker/deployment/hangar-frontend/Dockerfile
    depends_on:
      - 'backend'
    environment:
      # keep these in sync with gh-action!
      proxyHost: "http://hangar_backend:8080"
      authHost: "https://hangar-auth.benndorf.dev"
      host: "0.0.0.0"
      PUBLIC_HOST: "https://hangar.benndorf.dev"
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar.loadbalancer.server.port=1337"
      - "traefik.http.routers.hangar.rule=Host(`hangar.benndorf.dev`) || Host(`staging.hangarmc.dev`)"
      - "traefik.http.routers.hangar.entrypoints=web-secure"
      - "traefik.http.routers.hangar.tls=true"
      - "traefik.http.routers.hangar.tls.certresolver=default"
      - "traefik.http.routers.hangar.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangar.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web
  backend:
    image: "ghcr.io/papermc/hangar_backend"
    build:
      context: ../..
      dockerfile: docker/deployment/hangar-backend/Dockerfile
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SSO_CLIENT_ID: "${SSO_CLIENT_ID}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      SSO_API_KEY: "changeme"
    depends_on:
      - 'postgres'
      - 'mail'
    stdin_open: true
    labels:
      - "traefik.enable=false"
    volumes:
      - hangar_data:/hangar/uploads
    networks:
      - web
  postgres:
    image: "ghcr.io/papermc/hangar_postgres"
    build: ./postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: hydra,kratos
      POSTGRES_DB: hangar
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "3456:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
    labels:
      - "traefik.enable=false"
  mail:
    image: mailhog/mailhog:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-mail.loadbalancer.server.port=8025"
      - "traefik.http.routers.hangar-mail.middlewares=basicauth@file"
      - "traefik.http.routers.hangar-mail.rule=Host(`hangar-mail.minidigger.me`) || Host(`hangar-mail.benndorf.dev`)"
      - "traefik.http.routers.hangar-mail.entrypoints=web-secure"
      - "traefik.http.routers.hangar-mail.tls=true"
      - "traefik.http.routers.hangar-mail.tls.certresolver=default"
      - "traefik.http.routers.hangar-mail.tls.domains[0].main=minidigger.me"
      - "traefik.http.routers.hangar-mail.tls.domains[0].sans=*.minidigger.me"
    networks:
      - web

networks:
  web:
    name: traefik-overlay
    external: true

volumes:
  postgres_data:
  hangar_data:
